isce-framework/s1-reader

- src/sentinel1_reader/sentinel1_burst_slc.py
- src/sentinel1_reader/sentinel1_orbit_reader.py
- src/sentinel1_reader/sentinel1_reader.py
This PR adds the functionality of computing the azimuth carrier polynomials to the S1 reader for each burst (if requested).
This functionality will be needed for both COMPASS range/Doppler and geocoded CSLC workflow. To avoid code duplication, it makes sense that this functionality sits in the reader.
Note: the `polyfit` function in `sentinel1_burst_slc.py `needs help for the documentation.
> Adding azimuth carrier computation for bursts

- src/sentinel1_reader/sentinel1_orbit_reader.py
`os.listdir` [here](https://github.com/opera-adt/sentinel1-reader/blob/6eb464a392867352b895d0497cfcd040625ce011/src/sentinel1_reader/sentinel1_orbit_reader.py#L120) provides items without any reference to the source directory. The lack of a directory in the path breaks `get_swath_orbit_file_list` [here](https://github.com/opera-adt/sentinel1-reader/blob/6eb464a392867352b895d0497cfcd040625ce011/src/sentinel1_reader/sentinel1_orbit_reader.py#L41) and [here](https://github.com/opera-adt/sentinel1-reader/blob/6eb464a392867352b895d0497cfcd040625ce011/src/sentinel1_reader/sentinel1_orbit_reader.py#L74).
> prepend listdir results with path

- README.md
In the example we have provided a Dual-pol Vertical (DV) zip file but we passed ```pol=HH``` which does not exist in the zip file. Updating to ```pol=VV``` so that the example makes sense.
> README: switch to `pol=VV`

- src/sentinel1_reader/sentinel1_burst_slc.py
This PR gives `SentinelBurstSlc.get_az_carrier_poly` the ability to `polyfit` against azimuth and range values to allow for `carrier.eval(az, rng)`. This makes the `SentinelBurstSlc` carrier consistent with ISCE3 convention. Current use of use of `eval` only allows for azimuth and range indices as `eval` parameters.
> add carrier poly fit againt az/rng

- tests/download_data.py
This PR adds a unit test to download S1-A/B data. To avoid using credential info, data are downloaded from the AWS s3 seasia bucket containing S1-A/B data covering only South East Asia.
The PR should partially address issue #10. Another PR will follow for a test downloading the XML file and test  various reader functionalities.
Note: To download approx 4 GB of data takes around 10-15 min on average. It is recommended that this test runs nightly as a part of the CI suite.
> Unit test to download S1-A/B SAFE file

- bin/s1_read.py
- src/s1reader/__init__.py
- src/s1reader/s1_burst_slc.py
- src/s1reader/s1_orbit.py
- src/s1reader/s1_reader.py
This PR addresses #22 by adding a public-facing, generalized `load_bursts` method that:
1. loads from both zip and SAFE, 
2. doesn't require a tiff file to be found/included.
It is intended to replace the current public-facing `bursts_from_zip` method.
> generalized SAFE and zip reader

- README.md
- requirements.txt
+ README: 
- add license info, to be consistent with other opera-adt repos.
- and pre-alpha warning msg.
+ requirements:
- add `python>=3.9` to be consistent with `setup.cfg`
- comment out `isce3` as conda installed version does not work yet.
> README: add license and pre-alpha warning

- src/s1reader/s1_burst_slc.py
- src/s1reader/s1_reader.py
This PR extracts two more parameters called rank and prf. Even though Sentinel-1 Spec uses the short name prf I chose prf_raw_data to clarify that this prf is raw data prf and does not equal to the inverse of SLC azimuth_time_interval.
> extract rank and prf

- README.md
- src/s1reader/s1_burst_slc.py
This PR adds two more metadata to the burst class.
+ s1_slc_burst: add two more metadata:
- burst_duration
- swath_name
+ README: update usage to load_bursts()
> add burst metadata: burst_duration & swath_name

- src/s1reader/s1_burst_slc.py
- src/s1reader/s1_reader.py
This PR adds a method to the BurstSLC class to compute bistatic delay as described by [Gisinger et al 2021](https://ieeexplore.ieee.org/abstract/document/9115211). I have tried to put documentation in the code for a caveat about unclear initial bulk bistatic delay correction applied by ESA. At the moment I don't have a clear evidence if ESA has used the middle of the busrt of interest to compute their approximate bulk bistatic delay or the middle of the subswath 2. The latter has been mentioned by Gisinegr et al , but was not found in any ESA document so far.
> Bistatic delay

- src/s1reader/s1_burst_slc.py
- src/s1reader/s1_reader.py
This PR add functionality to compute range delay caused by Doppler shift as described by Gisinger et al 2021.
Note that to be able to reuse some the Carrier computation function that we had, I had to break it to two functions, one to compute Kt and one that computes the carrier and converts to phase in radian.
> Doppler shift

- src/s1reader/s1_reader.py
This PR adds ability to filter bursts from `s1_reader.load_bursts` by ID by adding a list of burst IDs to filter against.
```python
s1reader.load_bursts(safe_zip_path, orbit_path, i_subswath, pol)
s1reader.load_bursts(safe_dir_path, orbit_path, i_subswath, pol, ['t71_iw1_b848', 't71_iw1_b849'])
```
> retrieve bursts by ID

- src/s1reader/s1_reader.py
This PR fixes a bug In #37 when no burst IDs were found but partial find warning given.
In both calls below, 9 is not a valid ID.
```python
s1reader.load_bursts(path, orbit_path, i_subswath, pol, [9, 't71_iw2_b844'])
s1reader.load_bursts(path, orbit_path, i_subswath, pol, 9)
```
The resulting warnings are:
```bash
/home/lyu/miniconda3/envs/OPERA/lib/python3.9/site-packages/s1reader/s1_reader.py:493: UserWarning: Not all burst IDs found. Not found: {9}. Found: {'t71_iw2_b844'}
warnings.warn(warn_str)
/home/lyu/miniconda3/envs/OPERA/lib/python3.9/site-packages/s1reader/s1_reader.py:486: UserWarning: None of provided bursts IDs found
warnings.warn("None of provided bursts IDs found")
```
> fix partial IDs found

- src/s1reader/s1_reader.py
This PR should fix https://github.com/opera-adt/s1-reader/issues/43
The first line or sample with index 0 can be valid. Even-though normally there are few invalid lines or samples at the beginning of each burst, but in rare cases, like those reported in  https://github.com/opera-adt/s1-reader/issues/43 the first sample of a couple of bursts starts at 0 index, ie. no invalid sample at the beginning exists.
> bug fix for first valid line

- src/s1reader/s1_orbit.py
+ s1_orbit.get_orbit_file_from_list(): print out warning msg if no orbit file found from the given list (address #42)
+ s1_orbit.get_orbit_file_from_dir(): search file in orbit_dir with .EOF extension, instead of arbitrary, to provide more meaningful error msg if given a dir with files but w/o any *.EOF file.
> warning msg if no orbit file found for zip file

- src/s1reader/s1_orbit.py
This PR adds to the reader the capability of downloading orbits (precise or restituted) given a SAFE file.
It requires `requests` as a dependency and orbits are downloaded from SciHub using guest credentials.
The code was originally included in the Geocoded CSLC burst stack processor but it is more appropriate to attribute orbit download to the s1-reader
> Add orbit download functionality

- setup.cfg
- src/s1reader/__init__.py
- src/s1reader/version.py
Similar to https://github.com/opera-adt/COMPASS/pull/36, so that we only need to update version.py while cutting for a new release.
> add `version.py` as the single-source version history

- setup.cfg
- src/s1reader/__init__.py
- src/s1reader/version.py
This PR fixes the pip install error introduced in #54. The detailed changes are as below:
+ `setup.cfg`: setup the version number via `version.release_version`, instead of going through `__init__`, to avoid the circular imports that causes the pip install "ModuleNotFoundError"
+ `setup.cfg`: add `install_requires` and remove `[opptions.package_data]` to be consistent with compass
+ `__init__.py`: use absolute module import, to be consistent with the good style from pyresample module
+ `version.py`: remove the duplicated `__version__` variable.
> setup: access version w/o __init__ to avoid circular imports

- src/s1reader/s1_orbit.py
- src/s1reader/utils/plot_bursts.py
+ `s1_orbit.get_orbit_file_from_dir()`: add `auto_download` arg to automatically download the orbit file if not found. The default is False.
+ remove the unused get_orbit_file_from_list()
+ utils.plot_bursts.py: switch to get_orbit_file_from_dir()
> `s1_orbit.get_orbit_file_from_dir()`: add `auto_download` arg

- src/s1reader/s1_reader.py
While testing the burst database, I was downloading just the annotation files using https://github.com/avalentino/asfsmd . Since a lot of s1reader's functionality/usefulness comes from just the manifest and annotation files, it would be nice to allow optional loading without an orbit file or noise/calibration files.
The no-orbit case could be eventually changed by #41 to use the SAFE orbit. For the noise/calibration, it seems like since we already allow loading without the actual images here, we should then be able to skip the calibration on the image
https://github.com/opera-adt/s1-reader/blob/4000bc7a31d79e740212ab31495ca28ad0e2d426/src/s1reader/s1_reader.py#L844-L847
> make the noise/calibration/orbit reading optional

- src/s1reader/s1_etad.py
This PR adds `s1_etad.py`, which is a wrapper around the `s1etad` module from ESA. Given an `s1reader.Sentinel1BurstSlc` object, this sub-module will search, read the ETAD corrections, and/or resample into the full resolution, following the `s1etad` documentation (https://s1etad.readthedocs.io/en/latest/notebooks/S1-ETAD-Product_Quick_User_Guide.html).
Below is a simple example of usage.
```python
import s1reader
orbit_dir = '~/data/aux/S1/aux_poeorb'
eta_dir = './ETA'
slc_file = './SLC/S1A_IW_SLC__1SSV_20160922T230629_20160922T230656_013171_014F06_1463.zip'
orbit_file = s1reader.get_orbit_file_from_dir(slc_file, orbit_dir)
slc_burst = s1reader.load_bursts(slc_file, orbit_file, swath_num=1)[0]
eta_burst, eta = s1reader.s1_etad.get_eta_burst_from_slc_burst(slc_burst, eta_dir, verbose=True) …
```
> add s1-etad prep module for testing S1-ETAD products

- src/s1reader/s1_burst_slc.py
Fix a bug in `s1_burst_slc.Sentinel1BurstSlc.swath_name()` introduced in #77. This fix is required to run https://github.com/opera-adt/opera-notebooks/pull/1.
> bugfix in Sentinel1BurstSlc.swath_name()

- src/s1reader/s1_reader.py
_burst_from_safe_dir used os.listdir, which does not have "measurement" in the returned names like the zip file list does
this fixes #90
Before:
```
In [15]: b1 = s1reader.load_bursts("./S1A_IW_SLC__1SDV_20210410T140757_20210410T140824_037389_046804_70EA.SAFE", "./S1A_OPER_AUX_POEORB_OPOD_20210430T121835_V20210409T225942_20210411T005942.EOF", 1)[0]
In [16]: b1.tiff_path
Out[16]: ''
```
after:
```
In [49]: b1 = s1reader.load_bursts("./S1A_IW_SLC__1SDV_20210410T140757_20210410T140824_037389_046804_70EA.SAFE", "./S1A_OPER_AUX_POEORB_OPOD_20210430T121835_V20210409T225942_20210411T005942.EOF", 1)[0]
In [50]: b1.tiff_path
Out[50]: './S1A_IW_SLC__1SDV_20210410T140757_20210410T140824_037389_046804_70EA.SAFE/measurement/s1a-iw1-slc-vv-20210410t140759-20210410t140824-037389-046804-004.tiff'
```
> s1_reader: fix safe_path for directories

- src/s1reader/s1_annotation.py
Spelling fix so downstream processes don't have the same spelling error.
> azimith to azimuth spelling fix

- src/s1reader/s1_burst_slc.py
- src/s1reader/s1_info.py
Adds an option to get a quick bounding box for a frame. It'll use the preview/kml if it's there (for instance, in a full .zip file or SAFE with all files in it), otherwise it'll union all the burst `.bounds` (which is slower).
```
$ s1_info --bbox data/
Found 3 Sentinel-1 SLC products.
data/S1A_IW_SLC__1SDV_20221005T125539_20221005T125606_045307_056AA5_CB45.zip: [-105.269714, 31.20134, -102.25029, 33.238331]
data/S1A_IW_SLC__1SDV_20221010T010026_20221010T010052_045373_056CCC_4236.zip: [-106.049408, 30.349874, -103.073921, 32.378967]
data/S1A_IW_SLC__1SDV_20221017T125539_20221017T125606_045482_057043_39B5.zip: [-105.270958, 31.201355, -102.251465, 33.238483]
```
I wanted to add this for quick processing of a frame to know what area of a DEM to make:
```
$ s1_info --bbox …
```
> add a --bbox option to s1_info for frame bounds

- src/s1reader/s1_burst_slc.py
- tests/test_bursts.py
This allows a more coarse radar grid, as needed by some lookup tables such as the SET correction.
(this is mostly to help with cross-repo code duplication https://github.com/opera-adt/COMPASS/pull/91/files#diff-69dd9219c200228243e2fc9517100d1c8c2887874819ba403614548352b14b29R277-R292 )
> allow az_step/rg_step arguments to `as_isce3_radargrid`

- src/s1reader/s1_burst_slc.py
Now that the function `self.as_isce3_radargrid` has parameters for step sizes, we dont need to redo the logic to compute the coordinates.
This should fix #105 where the differing logic causes different coordinates.
It also allows us to remove redundant error checking that happens in the `as_isce3_radaragrid` function
> use radargrid step parameters to simplify `_steps_to_vecs`

- src/s1reader/version.py
This PR is to put a new version number for `s1-reader` to be packages with `RTC` and `COMPASS` for the upcoming gamma delivery.
> 0.1.5 -> 0.1.6 for gamma delivery

- src/s1reader/s1_orbit.py
- tests/test_orbit.py
This fixes #103 to get the right orbit file.
Currently we are returning "A" or "B" as a "sensor_id", then searching if the orbit file has that identifier (the single letter, which all orbit files have).
This 1. changes the parser to return the full S1A/S1B, 2. calls it the "mission_id" to match the language in the product spec https://sentinels.copernicus.eu/documents/247904/351187/Copernicus_Sentinels_POD_Service_File_Format_Specification
3. does further simplficication and cleanup of logic to make pylance/flake8 errors go away
The movement of function locations is to group similar functions together (`parse_safe_filename` and `get_file_name_tokens` were >100 lines apart before)
> s1_orbit: return S1A/S1B when parsing filename

- src/s1reader/s1_burst_id.py
Fixes #114.
We should add a unit test for this granule that compares it to the `burstId` in the XML metadata (which is available since it's a 2023 acquisition):
```
$ grep burstId S1A_IW_SLC__1SDV_20230115T162143_20230115T162211_046796_059C50_1250.SAFE/annotation/s1a-iw1-slc-vv-20230115t162145-20230115t162210-046796-059c50-004.xml
<burstId absolute="100514426">373734</burstId>
<burstId absolute="100514427">373735</burstId>
<burstId absolute="100514428">373736</burstId>
<burstId absolute="100514429">373737</burstId>
<burstId absolute="100514430">373738</burstId>
<burstId absolute="100514431">373739</burstId>
<burstId absolute="100514432">373740</burstId>
<burstId absolute="100514433">373741</burstId>
<burstId absolute="100514434">373742</burstId>
(mapping) staniewi:s1-reader$ grep …
```
> s1_burst_id: fix logic for track 174 anx crossing

- src/s1reader/s1_burst_slc.py
This PR is to fix the bug reported in #112. The reason for the crash was because DC polynomial interpolator was using incorrect data in the time axis.
This fix was tested using the sample dataset reported in the issue above, and was able to give the LUT as below:
Note on the tested dataset:
S1A_IW_SLC__1SSV_20150207T014953_20150207T015023_004511_005899_9C44.zip
S1A_OPER_AUX_POEORB_OPOD_20210305T194745_V20150206T225944_20150208T005944.EOF
Burst ID: `t064_135520_iw1`
> fix on DC polynomial interpolation for azimuth FM rate mismatch

- src/s1reader/version.py
This PR is to update the version for `s1-reader` before cutting the release for upcoming SAS delivery.
> 0.1.6 -> 0.1.7

- src/s1reader/s1_reader.py
if we download only the annotation files via `asfsmd`, we want to be able to load bursts without needing the RFI
> Make the RFI data loading optional

- src/s1reader/s1_annotation.py
- src/s1reader/s1_burst_id.py
- src/s1reader/s1_orbit.py
- src/s1reader/s1_reader.py
- tests/test_bursts.py
- tests/test_orbit.py
It has came into our attention that some of Sentinel-1 data has noticeable error in ANX time, which can cause incorrect computation of burst ID. More details about the issue can be found in #117.
This PR is to fix the issue by calculating the ANX time from orbit data. The screenshot below is the RTC outputs (VV polarization) before and after the ANX time correction.
Figure 1. Before the correction
.
Figure 2. After the correction
Information about the test dataset above:
On and around [Grenada](https://en.wikipedia.org/wiki/Grenada) (North of Venezuela)
`S1B_IW_SLC__1SDV_20211014T095918_20211014T095945_029130_0379DF_B302.zip`
`S1B_OPER_AUX_POEORB_OPOD_20211103T112606_V20211013T225942_20211015T005942.EOF`
> Correction of ascending node crossing time  (ANX time)

- .circleci/freeze-deps.sh
- LICENSE
- README.md
- environment.yaml
- src/s1reader/version.py
- bump to v0.2.0
- Various fixes for environments in preparation to put up on conda forge (which i will do after this is merged and the release is created)
- I switched the environment freezing script to the one @gmgunter made for `dophin`. It runs faster from using micromamba, but the only functional difference is that it pins to a specific conda hash for each package.  I didn't change the specfile, as I didn't want to mess something up if seongsu is already working on the docker preparation elsewhere.
> Release updates

- setup.cfg
Not sure why this was added, since [importlib.resources was available in python3.7](https://docs.python.org/3/library/importlib.resources.html) and we were never supporting older versions than that. We also dont seem to ever mention this package in the code.
> remove importlib_resources from `install_requires`

- src/s1reader/s1_annotation.py
- src/s1reader/s1_burst_slc.py
- src/s1reader/s1_reader.py
- src/s1reader/version.py
This PR is an attempt to fix the rare case that the list pf polynomials (azimuth FM rate or doppler centroid) does not have any overlap with the sensing start / stop of the burst. In that case, the azimuth FM rate mismatch correction finds the nearest polynomials in azimuth time, but the indices for polynomials (`index_start` and `index_end`) has the same value. When that happens interpolator from `InterpolatedUnivariateSpline` cannot be generated.
When that happens, the `index_start` and `index_end` are adjusted so that an`InterpolatedUnivariateSpline` gets to have valid parameters to create the interpolator.
When using the generated interpolator, optional parameter `ext=3` was set so that the interpolator returns the values at the left / right boundary values when the input parameter …
> Patch for "no polynomial" case for azimuth FM rate mitigation & handling the burst without burst polygon

- .git-blame-ignore-revs
The commit changed since we have "squash" on by default when merging PRs
> Fix .git-blame-ignore-revs for squashed commit hash

- src/s1reader/version.py
This PR is to bump the version of `s1reader` before cutting the release.
> bump version from `0.2.4->0.2.5`
